### ISSUE TITLE
Обмеження

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-56-fullstack-with-phones-db#1]
https://github.com/BohdanLuts/home-work-lesson-56-fullstack-with-phones-db/blob/d2b5e19651cc06607842d048ba12b5a98653e36f/server/models/phone.js#L18
- є ймовірність, що назва моделі одного бренду співпаде з назвою моделі іншого бренду. А от в рамках одного бренду назва моделі навряд чи співпаде, тому обмеження unique можна навісити саме на комбінацію model+brand. Інфо: https://sequelize.org/docs/v6/core-concepts/model-basics/#column-options (там де про // composite unique key.)

**Comment by BohdanLuts** [comment]
Під час тестування, все одно створюється сутність в межах одного бренду/моделі, навіть після зміни на унікальну комбінацію unique.

**Comment by pecourses** [comment]
Мій косяк. Не врахувала, що тут таблиці створюються міграціями. Якщо використовувати синхронізацію (тобто створювати таблички за моделями), то наведений вище варіант працює, а якщо створювати таблички міграціями, тоді варіант 
```
    await queryInterface.addConstraint('phones', {
      fields: ['model', 'brand'],
      type: 'unique',
      name: 'uniqueModelBrand',
    });
```
(https://sequelize.org/api/v6/class/src/dialects/abstract/query-interface.js~queryinterface#instance-method-addConstraint, приклад про UNIQUE, там можна кілька полів в масиві вказувати)
