### ISSUE TITLE
Зайва міграція

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-56-fullstack-with-phones-db#2]
https://github.com/BohdanLuts/home-work-lesson-56-fullstack-with-phones-db/blob/d2b5e19651cc06607842d048ba12b5a98653e36f/server/migrations/20230417073618-create-phone.js#L3
- як я розумію, результуюча міграція на створення таблиці інша, а ця заплутає sequelize-cli

**Comment by BohdanLuts** [comment]
Так, буде видалено
