### ISSUE TITLE
початкове значення

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-56-fullstack-with-phones-db#4]
https://github.com/BohdanLuts/home-work-lesson-56-fullstack-with-phones-db/blob/d2b5e19651cc06607842d048ba12b5a98653e36f/client/src/components/forms/PhoneForm/index.jsx#L16
- варто вказати false як дефолтне значення, інакше як не клікаєш жодного разу, то ругається на валідацію

**Comment by BohdanLuts** [comment]
Змінено на false
